# Live model
model: replicate/wan-2.1-1.3b-hotswap-lora-internal
test_model: replicate/wan-2.1-1.3b-hotswap-lora-internal-test

# Tests
predict:
  compare_outputs: false
  predict_timeout: 600
  test_cases:
    - inputs:
        prompt: "a LAEZEL portrait painting"
        replicate_weights: "https://replicate.delivery/xezq/begAR055rwyeb0sjY60xM01L9i2fJ8T11ofpHGfL6PCEYf2FF/trained_model.tar"
