name: Push

on:
  workflow_dispatch:
    inputs:
      models:
        description: 'Comma-separated list of models (standalone, trained) to push or "all"'
        type: string
        default: 'all'

jobs:
  cog-safe-push:
    runs-on: ubuntu-latest-4-cores

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install Cog
      run: |
        sudo curl -o /usr/local/bin/cog -L "https://github.com/replicate/cog/releases/latest/download/cog_$(uname -s)_$(uname -m)"
        sudo chmod +x /usr/local/bin/cog

    - name: cog login
      run: |
        echo ${{ secrets.COG_TOKEN }} | cog login --token-stdin

    - name: Install cog-safe-push
      run: |
        pip install git+https://github.com/replicate/cog-safe-push.git

    - name: Install custom nodes
      run: |
        python ./scripts/install_custom_nodes.py

    - name: Push selected models
      env:
        REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
      run: |
        if [ "${{ inputs.models }}" = "all" ]; then
          models="standalone, trained"
        else
          models="${{ inputs.models }}"
        fi

        for model in ${models//,/ }; do
          echo "==="
          echo "==="
          echo "=== Pushing $model"
          echo "==="
          echo "==="
          ./scripts/select-model $model
          cog-safe-push --config cog-safe-push-configs/$model.yaml -vv
        done
